name: trackr

services:
  server:
    image: code.tobtoby.net/tobtoby/trackr:latest
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      # Make sure to adjust to your own log file locations
      - ./trackr.log:/app/trackr.log
      - ./polls.log:/app/polls.log
      - ./service-account-config.json:/app/service-account-config.json
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-trixie@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: trackr_admin
      POSTGRES_DB: trackr
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trackr_admin -d trackr"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  # Adjust this based on your configuration
  postgres_password:
    file: postgres.pass

volumes:
  db_data:
