name: trackr

services:
  server:
    image: tbcr.tobtoby.net/trackr:0.1.6
    ports:
      - "8000:8000"
    volumes:
      # Make sure to adjust to your own log file locations
      - ./trackr.log:/app/trackr.log
      - ./polls.log:/app/polls.log
    environment:
      LOG_FILE: /app/trackr.log
      POLL_LOGS: /app/polls.log
      ADMIN_NAME: trackr_admin
      ADMIN_API_KEY_FILE: /run/secrets/admin_api_key
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: trackr_admin
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      DB_NAME: trackr
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING_FILE: /run/secrets/db_conn_string
      GOOSE_MIGRATION_DIR: ./postgresql/schema/
      SERVICE_ACCOUNT_PATH: /run/secrets/service_account_config
      TICK_INTERVAL_DEV: 5
      TICK_INTERVAL_PROD: 300
      DEVELOPMENT: true
    secrets:
      - admin_api_key
      - postgres_password
      - db_conn_string
      - service_account_config
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-trixie@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    ports:
      - "5431:5432"
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: trackr_admin
      POSTGRES_DB: trackr
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trackr_admin -d trackr"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  # Adjust this based on your configuration
  postgres_password:
    file: ./postgres.pass
  admin_api_key:
    file: ./admin-api-key.txt
  db_conn_string:
    file: ./db-conn-string.txt
  service_account_config:
    file: ./service-account-config.json

volumes:
  db_data:
