# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: trackr-be-secrets
  namespace: default
type: Opaque
data:
  service-account-config: |
    create a firebase service account config, then put the base64-encoded version here

# NOTE: Change and keep these credentials safe
stringData:
  admin-api-key: this-is-the-admin-api-key
  goose-dbstring: postgresql://trackr_admin:this-is-the-pg-password@trackr-db-0.trackr-db.default.svc.cluster.local:5432/trackr
  db-password: this-is-the-pg-password
---
apiVersion: v1
kind: Secret
metadata:
  name: trackr-db-secrets
  namespace: default
type: Opaque
# NOTE: Don't forget to synchronize this and the db-password above
stringData:
  postgres-password: this-is-the-pg-password
---
